### ISSUE TITLE
Session timeouts despite SSO_AUTH_ONLY_NOT_SESSION

### ISSUE THREAD

**Issue by tribut** [Timshel/vaultwarden#45] opened 2024-04-08 10:57 UTC
Hey, I've been running the current version of your sso-support branch for a few weeks now on a test installation. I have set `SSO_AUTH_ONLY_NOT_SESSION: "true"` because my IdP does not return a `refresh_token`.

But while the last version of the PR I had touched never logged anyone out, I am seeing frequent logouts after a few days of no contact with the server now.

[SSO.md claims](https://github.com/Timshel/vaultwarden/blob/b8c5e0fbb7f3f1f3d8dea5976884492c43189dc2/SSO.md?plain=1#L217) the generated refresh tokens are valid for a year, yet the generated tokens actually seem to be [valid for only 7 days](https://github.com/Timshel/vaultwarden/blob/f6d5e13e04a6f00368ab931b15456d74874fe662/src/auth.rs#L26).

This appears to be a regression or am I holding it wrong? The non-sso vaultwarden does not return a JWT as refresh token but simply some opaque data as far as I can tell and the client has never logged me out for not having contacted the server a few days.

**Comment by Timshel** [comment] 2024-04-08 16:00
Hey,

The doc is out of date, the refresh token was lowered to a 7 days idle timer (The one year was judged as too long, cf this [discussion](https://github.com/dani-garcia/vaultwarden/pull/3899#discussion_r1492983414)).

With activity, it can be extended indefinitely. But issue might be that not all activity trigger a refresh token.

**Comment by tribut** [comment] 2024-04-08 17:35
Ah yes, I remember reading that disussion. I believe it is a misunderstanding and the current behavior does not match the non-SSO experience.

According to [this bitwarden article](https://bitwarden.com/blog/configuring-bitwarden-clients-for-offline-access/#staying-logged-in-to-browser-extension-desktop-and-mobile-clients) "Offline Vault sessions will expire after 30 days".

What happens with the SSO patch right now is when the `refresh_token` expires, the client will automatically log out. This leads to the unfortunate consequence that a user who has stored their SSO password in the vault (but knows their master password) now has to somehow recover their SSO password before being able to unlock the vault again.

I suggest raising this to 30 days with a reference to that article. Unfortunately I couldn't find the code in the client that deals with the case of the `refresh_token` not being decodable as a JWT quickly. Hopefully I'll find time in the next days.

**Comment by Timshel** [comment] 2024-04-10 08:54
The current Vaultwarden non-SSO experience use a secret linked to the `device ` and never expire.

I isolated the addition of the JWT Refresh Token in a separate [PR](https://github.com/dani-garcia/vaultwarden/pull/4371). Will mention the suggestion of raising the expiration to 30 days.

**Comment by rizlas** [comment] 2024-04-10 15:42
Notice same behaviour too

**Comment by Timshel** [comment] 2024-04-10 15:58
I had some feedback from Blackdex in the other PR, I made the switch to 30 days in it and in `sso-support`.

So it will be in the next release, might wait a bit since I already had integrated the latest webvault change, so I might wait for the next Vaultwarden release.

**Comment by Timshel** [comment] 2024-04-16 18:18
Hey forgot to mention it on the changelog but it was released with `1.30.5-8`.

**Comment by rizlas** [comment] 2024-04-17 12:26
So the behavior is now the following: `"Offline Vault sessions will expire after 30 days. Except for mobile client applications, which will expire after 90 days."` ?

**Comment by Timshel** [comment] 2024-04-17 12:30
No 30 days (which can be extended) for all.

**Comment by rizlas** [comment] 2024-04-17 12:49
How it can be extended?

**Comment by Timshel** [comment] 2024-04-17 12:53
Each call to the `refresh` endpoint will generate a refresh token valid for the next 30 days.
Different actions trigger this such as a synchronize in the extension I believe or some navigation in the web app when the access token is expired.

**Closed** 2024-04-23 21:26 UTC

**Comment by NetSamurai** [comment] 2024-04-30 11:55
Hello @Timshel hate to ask a question that may be answered elsewhere, but say you're using `Authelia SSO` and your `2fa code` is in your `Bitwarden` account, protected by `Authelia`.

- Is the expected behavior that you can always log in without completing the 2FA challenge on your mobile device?
